-- Esquema inicial para MiPortafolio en Supabase/PostgreSQL
-- Ejecutar en el SQL Editor de Supabase.
-- La aplicacion se conecta con JDBC usando el usuario postgres.

BEGIN;

-- Mantiene actualizado updated_at cuando cambia una fila.
CREATE OR REPLACE FUNCTION public.actualizar_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(60) NOT NULL,
    nombre      VARCHAR(150) NOT NULL,
    rol         VARCHAR(20) NOT NULL DEFAULT 'usuario',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT usuarios_rol_valido CHECK (rol IN ('usuario', 'admin')),
    CONSTRAINT usuarios_admin_reservado CHECK (
        (lower(trim(email)) = 'samircenfe17@gmail.com' AND rol = 'admin')
        OR
        (lower(trim(email)) <> 'samircenfe17@gmail.com' AND rol = 'usuario')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_email_normalizado_unico
    ON public.usuarios (lower(trim(email)));

CREATE TABLE IF NOT EXISTS public.archivos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255) NOT NULL,
    descripcion TEXT,
    tipo        VARCHAR(100) NOT NULL,
    url         TEXT NOT NULL,
    usuario_id  BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT archivos_usuario_fk
        FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS archivos_usuario_id_idx
    ON public.archivos (usuario_id);

CREATE INDEX IF NOT EXISTS archivos_created_at_idx
    ON public.archivos (created_at DESC);

DROP TRIGGER IF EXISTS usuarios_actualizar_updated_at ON public.usuarios;
CREATE TRIGGER usuarios_actualizar_updated_at
    BEFORE UPDATE ON public.usuarios
    FOR EACH ROW
    EXECUTE FUNCTION public.actualizar_updated_at();

DROP TRIGGER IF EXISTS archivos_actualizar_updated_at ON public.archivos;
CREATE TRIGGER archivos_actualizar_updated_at
    BEFORE UPDATE ON public.archivos
    FOR EACH ROW
    EXECUTE FUNCTION public.actualizar_updated_at();

COMMIT;

-- IMPORTANTE:
-- 1. No se inserta un admin aqui porque la contrasena debe ser un hash BCrypt
--    generado por la aplicacion, nunca una contrasena en texto plano.
-- 2. El registro publico debe crear siempre rol='usuario'. Para crear tu cuenta
--    administradora, registra primero el correo reservado desde la aplicacion
--    despues de ajustar RegistroServlet/AuthService, o inserta una fila con un
--    hash BCrypt real generado por BCrypt.hashpw(...).
-- 3. La restriccion usuarios_admin_reservado impide otros administradores a
--    nivel de base de datos, pero las rutas Java tambien deben comprobar rol.
